CREATE USER FIDE_PLAZA_MEDICA IDENTIFIED BY PLAZAMEDICA;

GRANT CONNECT, RESOURCE, DBA TO FIDE_PLAZA_MEDICA;

GRANT CREATE SESSION TO FIDE_PLAZA_MEDICA;

ALTER USER FIDE_PLAZA_MEDICA ACCOUNT UNLOCK;

--1
CREATE TABLE FIDE_ROL_TB (
    ID_ROL NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP
);

--2
CREATE TABLE FIDE_USUARIO_TB (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR2(100),
    PASSWORD VARCHAR2(100),
    ROL_ID NUMBER,
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP,
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ROL_ID) REFERENCES FIDE_ROL_TB(ID_ROL)
);

--3
CREATE TABLE FIDE_CATEGORIA_PRODUCTO_TB (
    ID_CATEGORIA_PRODUCTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP
);

--4
CREATE TABLE FIDE_PRODUCTO_TB (
    ID_PRODUCTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    DESCRIPCION VARCHAR2(255),
    PRECIO NUMBER,
    ID_CATEGORIA_PRODUCTO NUMBER,
    STOCK NUMBER,
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP,
    CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA_PRODUCTO) REFERENCES FIDE_CATEGORIA_PRODUCTO_TB(ID_CATEGORIA_PRODUCTO)
);

--5
CREATE TABLE FIDE_MEDICAMENTO_TB (
    ID_MEDICAMENTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    DESCRIPCION VARCHAR2(255),
    ID_CATEGORIA_PRODUCTO NUMBER,
    STOCK NUMBER,
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP,
    CONSTRAINT FK_MEDICAMENTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA_PRODUCTO)
        REFERENCES FIDE_CATEGORIA_PRODUCTO_TB(ID_CATEGORIA_PRODUCTO)
);

--6
CREATE TABLE FIDE_PACIENTE_TB (
    ID_PACIENTE NUMBER PRIMARY KEY,
    CEDULA VARCHAR2(20),
    NOMBRE VARCHAR2(100),
    APELLIDO VARCHAR2(100),
    FECHA_NACIMIENTO DATE,
    SEXO VARCHAR2(1),
    DIRECCION VARCHAR2(200),
    CORREO VARCHAR2(100),
    TELEFONO VARCHAR2(20),
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP
);

--7
CREATE TABLE FIDE_CONTACTO_EMERGENCIA_TB (
    ID_CONTACTO NUMBER PRIMARY KEY,
    ID_PACIENTE NUMBER,
    NOMBRE VARCHAR2(100),
    TELEFONO VARCHAR2(20),
    PARENTESCO VARCHAR2(50),
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP,
    CONSTRAINT FK_CONTACTO_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES FIDE_PACIENTE_TB(ID_PACIENTE)
);

--8
CREATE TABLE FIDE_ALERTA_STOCK_TB (
    ID_ALERTA NUMBER PRIMARY KEY,
    ID_PRODUCTO NUMBER,
    UMBRAL NUMBER,
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP,
    CONSTRAINT FK_ALERTA_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES FIDE_PRODUCTO_TB(ID_PRODUCTO)
);

--9
CREATE TABLE FIDE_ESPECIALIDAD_TB (
    ID_ESPECIALIDAD NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP
);

--10
CREATE TABLE FIDE_MEDICO_TB (
    ID_MEDICO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    TELEFONO VARCHAR2(20),
    CORREO VARCHAR2(100),
    ID_ESPECIALIDAD NUMBER,
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP,
    CONSTRAINT FK_MEDICO_ESPECIALIDAD FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES FIDE_ESPECIALIDAD_TB(ID_ESPECIALIDAD)
);

--11
CREATE TABLE FIDE_HORARIO_MEDICO_TB (
    ID_HORARIO NUMBER PRIMARY KEY,
    ID_MEDICO NUMBER,
    DIA VARCHAR2(15),
    HORA_INICIO VARCHAR2(10),
    HORA_FIN VARCHAR2(10),
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP,
    CONSTRAINT FK_HORARIO_MEDICO FOREIGN KEY (ID_MEDICO) REFERENCES FIDE_MEDICO_TB(ID_MEDICO)
);

--12
CREATE TABLE FIDE_CONSULTA_TB (
    ID_CONSULTA NUMBER PRIMARY KEY,
    ID_PACIENTE NUMBER,
    ID_MEDICO NUMBER,
    FECHA_CONSULTA DATE,
    DIAGNOSTICO VARCHAR2(500),
    OBSERVACIONES VARCHAR2(500),
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP,
    CONSTRAINT FK_CONSULTA_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES FIDE_PACIENTE_TB(ID_PACIENTE),
    CONSTRAINT FK_CONSULTA_MEDICO FOREIGN KEY (ID_MEDICO) REFERENCES FIDE_MEDICO_TB(ID_MEDICO)
);

--13
CREATE TABLE FIDE_RECETA_TB (
    ID_RECETA NUMBER PRIMARY KEY,
    ID_CONSULTA NUMBER,
    FECHA_ENTREGA DATE,
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP,
    CONSTRAINT FK_RECETA_CONSULTA FOREIGN KEY (ID_CONSULTA) REFERENCES FIDE_CONSULTA_TB(ID_CONSULTA)
);

--14
CREATE TABLE FIDE_DETALLE_RECETA_TB (
    ID_DETALLE_RECETA NUMBER PRIMARY KEY,
    ID_RECETA NUMBER,
    MEDICAMENTO VARCHAR2(200),
    DOSIS VARCHAR2(100),
    DURACION VARCHAR2(100),
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP,
    CONSTRAINT FK_DETALLE_RECETA FOREIGN KEY (ID_RECETA) REFERENCES FIDE_RECETA_TB(ID_RECETA)
);

--15
CREATE TABLE FIDE_EXAMEN_TB (
    ID_EXAMEN NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    TIPO VARCHAR2(100),
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP
);

--16
CREATE TABLE FIDE_RESULTADO_EXAMEN_TB (
    ID_RESULTADO_EXAMEN NUMBER PRIMARY KEY,
    ID_EXAMEN NUMBER,
    ID_PACIENTE NUMBER,
    FECHA_RESULTADO DATE,
    RESULTADO VARCHAR2(500),
    OBSERVACIONES VARCHAR2(500),
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP,
    CONSTRAINT FK_RESULTADO_EXAMEN FOREIGN KEY (ID_EXAMEN) REFERENCES FIDE_EXAMEN_TB(ID_EXAMEN),
    CONSTRAINT FK_RESULTADO_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES FIDE_PACIENTE_TB(ID_PACIENTE)
);

--17
CREATE TABLE FIDE_TIPO_PAGO_TB (
    ID_TIPO_PAGO NUMBER PRIMARY KEY,
    NOMBRE_TIPO_PAGO VARCHAR2(100),
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP
);

--18
CREATE TABLE FIDE_FACTURA_TB (
    ID_FACTURA NUMBER PRIMARY KEY,
    ID_PACIENTE NUMBER,
    FECHA TIMESTAMP,
    ID_TIPO_PAGO NUMBER,
    TOTAL NUMBER,
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP,
    CONSTRAINT FK_FACTURA_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES FIDE_PACIENTE_TB(ID_PACIENTE),
    CONSTRAINT FK_FACTURA_PAGO FOREIGN KEY (ID_TIPO_PAGO) REFERENCES FIDE_TIPO_PAGO_TB(ID_TIPO_PAGO)
);

--19
CREATE TABLE FIDE_DETALLE_FACTURA_TB (
    ID_DETALLE_FACTURA NUMBER PRIMARY KEY,
    ID_FACTURA NUMBER,
    ID_PRODUCTO NUMBER,
    CANTIDAD NUMBER,
    PRECIO_UNITARIO NUMBER,
    SUBTOTAL NUMBER,
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP,
    CONSTRAINT FK_DETALLE_FACTURA FOREIGN KEY (ID_FACTURA) REFERENCES FIDE_FACTURA_TB(ID_FACTURA),
    CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES FIDE_PRODUCTO_TB(ID_PRODUCTO)
);

--20
CREATE TABLE FIDE_MOVIMIENTO_INVENTARIO_TB (
    ID_MOVIMIENTO NUMBER PRIMARY KEY,
    ID_PRODUCTO NUMBER,
    FECHA TIMESTAMP,
    CANTIDAD NUMBER,
    TIPO_MOVIMIENTO VARCHAR2(50),
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP,
    CONSTRAINT FK_MOVIMIENTO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES FIDE_PRODUCTO_TB(ID_PRODUCTO)
);

--21
CREATE TABLE FIDE_CITA_TB (
    ID_CITA NUMBER PRIMARY KEY,
    ID_PACIENTE NUMBER,
    ID_MEDICO NUMBER,
    FECHA DATE,
    HORA VARCHAR2(10),
    MOTIVO VARCHAR2(255),
    CREATED_BY VARCHAR2(100),
    CREATED_ON TIMESTAMP,
    MODIFIED_BY VARCHAR2(100),
    MODIFIED_ON TIMESTAMP,
    CONSTRAINT FK_CITA_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES FIDE_PACIENTE_TB(ID_PACIENTE),
    CONSTRAINT FK_CITA_MEDICO FOREIGN KEY (ID_MEDICO) REFERENCES FIDE_MEDICO_TB(ID_MEDICO)
);